auth/urls.py
from django.conf.urls import url

from . import views

app_name = 'auth'

urlpatterns = [
	url(r'^$',views.index,name='index'),
    url(r'^signin/$', views.signin, name='signin'),
    url(r'^signup/$',views.signup,name='signup'),
    url(r'^signout/$',views.signout,name='logout'),
    url(r'^register/$',views.register,name='register'),
]

igconnect/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'igconnect.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^auth/',include('auth.urls',namespace='auth')),
    url(r'^forum/',include('forum.urls',namespace='forum')),
    url(r'^dashboard/',include('dashboard.urls',namespace='dashboard')),
    url(r'^message/',include('message.urls',namespace='message')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}),
    url(r'^profile/',include('profileSpace.urls',namespace='profile')),
    url(r'^search/',include('searchig.urls',namespace='searchig')),
    url(r'^event/',include('event.urls',namespace='event')),
)

profileSpace/urls.py
from django.conf.urls import url

from . import views

app_name = 'profileSpace'

urlpatterns = [
	url(r'^view/?(?P<username>\w+)?/?$',views.index,name='index'),
	url(r'^view$',views.index,name='index'),
	url(r'^edit/$',views.edit,name='edit'),

]

templates/profile/completeProfile.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block title %}
Complete Profile
{% endblock %}

{% block content %}
<script src="{% static 'js/profile/profile.js' %}" ></script>
<h3>Complete Your Profile</h3>
<div class = "row">
	<form class = "col s12 completeForm" action = "{% url 'profile:complete' %}" method = "post">
		{% csrf_token %}
		<div class = "row">
			<div class="input-field col s4">
				<input type="text" class="validate phoneNo" name = "phoneNo" required="" max-length = "10" autofocus>
				<label for="first_name">Phone Number</label>
			</div>
			<div class = "row">
				<div class="input-field col s4">
					<div class="switch">
						<label>
							Share
							<input type="checkbox">
							<span class="lever"></span>
							Don't share
						</label>
					</div>
				</div>
			</div>
			<div class = "row">
				<div class="input-field col s12">
					<textarea class="materialize-textarea aboutMe" max-length = "100" required=""></textarea>
					<label for="textarea1">About Me</label>
				</div>
			</div>
			<div class = "row MOOCList" count="1">
				<input type = "button" class = "btn addMOOC" value="Add More MOOC" onclick = "addMOOC()"/>
				<div class="input-field col s12">
					<textarea class="materialize-textarea" id = "MOOC1" max-length = "100" required=""></textarea>
					<label for="textarea1">MOOC</label>
				</div>
			</div>
			<div class = "row researchPaperList" count="1">
				<input type = "button" class = "btn addResearch" value="Add More Research Paper" onclick = "addResearch()"/>
				<div class="input-field col s12">
					<textarea class="materialize-textarea" id = "researchPaper1" max-length = "100" required=""></textarea>
					<label for="textarea1">Reseach Paper</label>
				</div>
			</div>
			<div class = "row conferenceList" count = "1">
				<input type = "button" class = "btn addConference" value="Add More Conference" onclick="addConference()" />
				<div class="input-field col s12">
					<textarea class="materialize-textarea" id = "conference1" max-length = "100" required=""></textarea>
					<label for="textarea1">Conference Attended</label>
				</div>
			</div>
		</div>
	</form>
	<div class = "row">
		<input class = "btn" type = "button" value = "submit" />
	</div>
</div>
{% endblock %}

templates/profile/edit.html
{% extends 'base/base.html' %}

{% block title %}
	Edit Profile
{% endblock %}
{% load staticfiles%}
{% block content %}
<script src="{% static 'js/profile/profile.js' %}" ></script>
<div class = "container">
<div class = "row">
	<div class = "col m8 l8 s12 offset-m2 offset-l2">
	<form class = "editForm col s12 " action = "{% url 'profile:edit' %}" method = "post">
		{% csrf_token %}
		
			<div class = "input-field center-align ">
					<h2 class = "thin-letters-2">Edit Your Profile</h2>
			</div>
			<div class = "divider"></div>
			<div class = "section"></div>

			<div class = "row">
			<div class="input-field">
				<input type="text" class="validate first_name" name = "regNo" value = "{{userData.user.first_name}}" required="" autofocus>
				<label for="first_name">First Name:</label>
			</div>
		</div>

		<div class = "row">
			<div class="input-field">
				<input type="text" class="validate last_name" name = "regNo" value = "{{userData.user.last_name}}" required="" autofocus>
				<label for="first_name">Last Name</label>
			</div>
		</div>
		<div class = "row">
			<div class="input-field">
				<input type="email" class="validate email" name = "regNo" value = "{{userData.user.email}}" required="" autofocus>
				<label for="first_name">Email</label>
			</div>
		</div>
		<div class = "row">
			<div class="input-field">
				<input type="text" class="validate regNum" name = "regNo" value = "{{userData.regNum}}" required="" autofocus>
				<label for="first_name">Registration Number</label>
			</div>
		</div>

		<div class = "row" >
			<div class="input-field">
				<select class='branch' selected = "{{userData.branch}}">
					<option value="" disabled selected>Choose your branch</option>
					<option value="1">Civil Engineering</option>
					<option value="2">Mechanical Engineering</option>
					<option value="3">Electrical And Electronics Engineering</option>
					<option value="4">Electronics And Communication Engineering</option>
					<option value="5">Computer Science And Engineering</option>
					<option value="6">Chemical Engineering</option>
					<option value="7">Bio-Technology</option>
					<option value="8">Metallurgical And Material Engineering</option>
				</select>
				<label>Select Branch</label>
			</div>
		</div>
		<div class = "row">
			<div class="input-field">
				<select class = 'level' selected="{{userData.level}}">
					<option value="" disabled selected>Choose your Level</option>
					<option value="1">B.Tech I</option>
					<option value="2">B.Tech II</option>
					<option value="3">B.Tech III</option>
					<option value="4">B.Tech IV</option>
					<option value="5">M.Tech I</option>
					<option value="6">M.Tech II</option>
					<option value="7">Research Scholar</option>
				</select>
				<label>Select Level</label>
			</div>
		</div>

		<script>
			//preselecting the value of select tags
			//couldn't find any other better way
			var changeSelect = function(index1,index2){
                $('.branch').val(index1);
                $('.level').val(index2);
             //   console.log(index1)
            }
            changeSelect({{userData.branch}},{{userData.level}});
			
		</script>
		<div class = "row">
			<label>Check this again</label>
			<table class = "bordered skillTable">
				<thead>
					<th>Skill</th>
					<th>Check</th>
				</thead>
				<tbody>
					
					{% for skill in skillList %}
					<tr>
						<td>{{skill.skillName}}</td>
						<td> <div class="switch">
							<label>
								I Don't know
								<b></b>
								{% if skill in userData.skillList %}
								<input type="checkbox" name="{{skill.id}}" checked>
								{% else %}
								<input type="checkbox" name="{{skill.id}}">
								{% endif%}
								<span class="lever"></span>
								I Know
							</label>
						</div></td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
		<div class = "row">
			<div class="input-field col s6 l6 m6">
				<input type="text" class="validate phoneNum" name = "phoneNo" required="" value = "{{userData.phoneNo}}"max-length = "10" autofocus>
				<label for="first_name">Phone Number</label>
			</div>
				<div class="input-field col s6 l6 m6">
					<div class="switch">
						<label>
							Don't Share
							{% if userData.shareNo == 0 %}
							<input type="checkbox" class = "share">
							{% else %}
							<input type="checkbox" class = "share" checked>
							{% endif %}
							<span class="lever"></span>
							share
						</label>
					</div>
				</div>
		</div>
			<div class = "row">
				<div class="input-field">
					<textarea class="materialize-textarea aboutMe" max-length = "100" required="">{{userData.aboutMe}}</textarea>
					<label for="textarea1">About Me</label>
				</div>
			</div>
			<div class = "row MOOCList" count="{{userData.MOOCList | length}}">
				{% for MOOC in userData.MOOCList %}
					<div class='input-field'><textarea class='materialize-textarea' id = 'MOOC{{loop.index}}' max-length = '100'>{{MOOC}}</textarea><label for='textarea1'></label></div>
				{% endfor %} 
			</div>

			<div class = "row">
				<input type = "button" class = "btn addMOOC" value="Add MOOC" onclick = "addMOOC()"/>
			</div>

			<div class = "row researchPaperList" count="{{userData.MOOCList | length}}">
				{% for researchPaper in userData.researchPaperList %}
					<div class='input-field col s6 m6 l6'><textarea class='materialize-textarea' id = 'researchPaper{{loop.index}}' max-length = '100'>{{researchPaper}}</textarea><label for='Subject'></label></div>
					<div class='input-field'><textarea class='materialize-textarea' id = 'researchPaper{{loop.index}}' max-length = '100'>{{researchPaper}}</textarea><label for='Subject'></label></div>
				{% endfor %}
			</div>

			<div class = "row">
				<input type = "button" class = "btn addResearch" value="Add Research Paper" onclick = "addResearch()"/>
			</div>

			<div class = "row conferenceList" count = "0">
				{% for conference in userData.conferenceList %}
					<div class='input-field'><textarea class='materialize-textarea' id = 'conference{{loop.index}}' max-length = '100'>{{conference}}</textarea><label for='textarea1'></label></div>
				{% endfor %}
			</div>

			<div class = "row">
				<input type = "button" class = "btn addConference" value="Add More Conference" onclick="addConference()" />
			</div>
			<div class = "divider"></div>
			<div class = "section"></div>
		<div class = "row">
			<input type = "button" class = "btn" onclick="check()" value="Complete Edit"/>
		</div>
	</form>
</div>
</div>
<div>
{% endblock %}

templates/profile/profile.html
{% extends 'base/base.html' %}
{% block title %}
	Profile
{% endblock %}
{% load staticfiles %}
{% block content %}
{% csrf_token %}
<div class = "container">
	<div class = "row thin-letters-3">
		<div class = "col s12 m4 s4">
			<div class="row">
				<div class="col s12 m12 l12">
					<div class="card">
						<div class="card-image">
							{% if profilePic %}
							<img src = "https://wsdc.nitw.ac.in/student/assets/upload/thumbs/{{userData.regNum}}.jpg" />
							{% else %}
								<img src="{% static 'images/profile_images/sample.png' %}">
							{% endif %}
							<span class="card-title"><b>{{userData.user.username}}</b></span>
						</div>
						<div class="card-content">
							<p>{{userData.aboutMe}}</p>
						</div>
						<div class="card-action">
							{% if user.username == userData.user.username %}
							<button class = "btn" onclick = "javascript: window.location = '{% url 'profile:edit' %}'">Edit Profile</button>
							{% else %}
							
							<a href="#">IGHANDLE</a>
							{% if sendMessage == True %}
								<a href="#" id="message">Send Message</a>
							{% endif %}
							{% endif %}
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class = "col s12 m8 l8">
			<ul class="collection">
				<li class="collection-item avatar">
					<i class = "material-icons circle red">perm_identity</i>
					<span class="title"><b>Overview</b></span>
					<p>Name: {{userData.user.first_name}} {{userData.user.last_name}}<br/>
						Registration Number: {{userData.regNum}}<br/>
						Branch: {{userData.branch}}<br/>
						Year: {{userData.level}}<br/>
					</p>
					<a href="#!" class="secondary-content"><i class="material-icons">grade</i></a>
				</li>
				<li class="collection-item avatar">
					<i class="material-icons circle blue">contacts</i>
					<span class="title"><b>Contacts</b></span>
					<p>Email Address: {{userData.user.email}} <br>
						Phone: {% if userData.shareNo == 1 %}
							{{userData.phoneNo}}
						{% else %}
							Phone Number is private
						{% endif %}
					</p>
					<a href="#!" class="secondary-content"><i class="material-icons">grade</i></a>
				</li>
				<li class="collection-item avatar">
					<i class="material-icons circle blue">work</i>
					<span class="title"><b>Projects</b></span>
					<p>
						{% if projects %}
							{% for project in projects %}
								<a href = "/dashboard/viewProject/?projectId={{project.id}}">{{project.projectName}}</a><br/>
							{% endfor %}
						{% else %}
							None.
						{% endif %}
					</p>
					<a href="#!" class="secondary-content"><i class="material-icons">grade</i></a>
				</li>

				<li class="collection-item avatar">
					<i class="material-icons circle green"><b>redeem</b></i>
					<span class="title"><b>Skills</b></span>
					<p>
						{% if userData.skillList %}
							{% for skill in userData.skillList %}
								{{skill}}<br/>
							{% endfor %}
						{% else %}
							None.
						{% endif %}
					</p>
					<a href="#!" class="secondary-content"><i class="material-icons">grade</i></a>
				</li>
				<li class="collection-item avatar">
					<i class="material-icons circle purple"><b>note_add</b></i>
					<span class="title"><b>MOOCs</b></span>
					<p>
						{% if userData.MOOCList %}
							{% for MOOC in userData.MOOCList %}
								{{MOOC}}<br/>
							{% endfor %}
						{% else %}
							None.
						{% endif %}
					</p>
					<a href="#!" class="secondary-content"><i class="material-icons">grade</i></a>
				</li>
				<li class="collection-item avatar">
					<i class="material-icons circle orange">library_books</i>
					<span class="title"><b>Research Paper</b></span>
					<p>
						{% if userData.researchPaperList%}
							{% for research in userData.researchPaperList %}
								{{research}}<br/>
							{% endfor %}
						{% else %}
							None.
						{% endif %}
					</p>
					<a href="#!" class="secondary-content"><i class="material-icons">grade</i></a>
				</li>
				<li class="collection-item avatar">
					<i class="material-icons circle yellow">view_column</i>
					<span class="title"><b>Conference Attended</b></span>
					<p>
						{% if userData.conferenceList %}
							{% for conference in userData.conferenceList %}
								{{conference}}<br/>
							{% endfor %}
						{% else %}
							None.
						{% endif %}
					</p>
					<a href="#!" class="secondary-content"><i class="material-icons">grade</i></a>
				</li>
			</ul>
		</div>
	</div>
</div>
<script type="text/javascript" src = "{% static 'js/sendmessage.js' %}"></script>

<div id="messageModal" class="modal bottom-sheet">
	<div class="modal-content">
		<h4 class='modal-header'>Send Message to {{userData.user.username}}</h4>
		<div class = "row">
			
				<textarea class="materialize-textarea" name="body" id="body"></textarea>
			
		</div>

	</div>


	<div class="modal-footer">
		<a class="waves-effect waves-light btn green" id="send" to="{{to}}" from="{{from}}" ><i class="material-icons right">done</i>Send</a>
	</div>
</div>
{% endblock %}