auth/urls.py
from django.conf.urls import url

from . import views

app_name = 'auth'

urlpatterns = [
	url(r'^$',views.index,name='index'),
    url(r'^signin/$', views.signin, name='signin'),
    url(r'^signup/$',views.signup,name='signup'),
    url(r'^signout/$',views.signout,name='logout'),
    url(r'^register/$',views.register,name='register'),
]

event/urls.py
from django.conf.urls import url

from . import views

app_name = 'event'

urlpatterns = [
	url(r'^$',views.index,name='index'),
    url(r'^addEvent/$', views.addEvent, name='addEvent'),
    url(r'^viewall/$',views.viewall,name='viewall'),
    url(r'^viewall/(?P<pageNo>\d+)/$',views.viewall,name='viewall'),
]

igconnect/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'igconnect.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^auth/',include('auth.urls',namespace='auth')),
    url(r'^forum/',include('forum.urls',namespace='forum')),
    url(r'^dashboard/',include('dashboard.urls',namespace='dashboard')),
    url(r'^message/',include('message.urls',namespace='message')),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}),
    url(r'^profile/',include('profileSpace.urls',namespace='profile')),
    url(r'^search/',include('searchig.urls',namespace='searchig')),
    url(r'^event/',include('event.urls',namespace='event')),
)

searchig/urls.py
from django.conf.urls import url

from . import views

app_name = 'searchig'

urlpatterns = [
	url(r'^$',views.index,name='index'),
	url(r'^query/(?P<searchWords>[\w|\W]+)/$',views.query,name='query'),
	url(r'^fromDash/$',views.fromDash,name='queryFromDash'),
]

event/models.py
from django.db import models
from django.contrib.auth.models import User
from djangotoolbox.fields import ListField,EmbeddedModelField
from django.core import serializers
from django_mongodb_engine.contrib import MongoDBManager
from django.utils.formats import get_format
from auth.models import Skill
# Create your models here.


class Event(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    eventName = models.CharField(max_length=50)
    startdate = models.DateField()
    enddate = models.DateField()
    description = models.CharField(max_length=50)
    organiser = models.CharField(max_length=50)
    mentorList = ListField(EmbeddedModelField(User))
    skillList = ListField(EmbeddedModelField(Skill))
    
    def __str__(self):
        return self.eventName

event/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404,render,redirect
from django.contrib.auth import authenticate,login
from django.contrib.auth import logout
from django.contrib.auth.models import User
from auth.models import Skill
from djangotoolbox.fields import ListField,EmbeddedModelField
from dashboard.forms import DocumentForm
from datetime import datetime
from django.core.paginator import Paginator
from .models import Event
import json,os,pymongo
from django.core.serializers.json import DjangoJSONEncoder
from bson.json_util import dumps
from django.core import serializers
from django.db.models import Q
from django.views.decorators.csrf import csrf_exempt, csrf_protect
# Create your views here.

client = pymongo.MongoClient('0.0.0.0', 27017)
db = client.igconnect_db
@csrf_exempt
def index(request,pageNo=None):

    return redirect('/event/viewall')


def addEvent(request):
    if not  request.user.is_authenticated() or not request.user.is_active == True:
		redirect("/auth/")
    if request.method=="POST":
        requestReceived=json.loads(request.POST.get("event"))
        json.dumps(requestReceived)
        eventName=requestReceived['eventname']
        eventDescription=requestReceived['eventDescription']
        organiser=requestReceived['organiser']
        skills=requestReceived['skills']
        sdate=requestReceived['startdate']
        edate=requestReceived['enddate']
        skillList=[]
        for skillId in skills:
            skill=Skill.objects.get(id=skillId)
            skillList.append(skill)

        mentors=requestReceived['mentors']
        mentorList=[]
        for username in mentors:
            user=User.objects.get(username=username)
            mentorList.append(user)
        event=Event(user=request.user,eventName=eventName,startdate=sdate,enddate=edate,description=eventDescription,organiser=organiser,mentorList=mentorList,skillList=skillList)
        event.save()
        return HttpResponse()


    else:

		users=User.objects.all();
		skills=Skill.objects.all();
		if request.user.is_authenticated():
			return render(request,'event/addevent.html',{'skills':skills,'users':users,'username':request.user.username});	
		else:
			return redirect("/auth/")
@csrf_exempt
def viewall(request,pageNo=None):
    if request.user.is_authenticated() and request.user.is_active == True:
        eventList=Event.objects.order_by('eventName')
        paginator = Paginator(eventList,3)
        
        if request.method == 'POST':
            print "hi"
            data = json.loads(request.POST['data'])
            json.dumps(data)
            print "see u again"
            return categorise(data)

        if pageNo is None: 
            events = paginator.page(1)
            eventList = events.object_list
            myevents = list()
            for event in eventList:
                myUser = {
                    'first_name':event.user.first_name,
                    'last_name':event.user.last_name
                }

                myEvent = {
                    'startdate':event.startdate,
                    'enddate':event.enddate,
                    'id':event.id,
                    'user':myUser,
                    'eventName':event.eventName,
                    'eventDescription':event.description,
                    'skillList':event.skillList,
                    'mentorList':event.mentorList,

                }

                myevents.append(myEvent)
            users=User.objects.all()
            return render(request,'event/showevent.html',{'events':myevents,'username':request.user.username,'users':users})
        else:
            events = paginator.page(pageNo)
            eventList = events.object_list
            myevents = list()
            for event in eventList:
                myUser = {
                    'first_name':event.user.first_name,
                    'last_name':event.user.last_name
                }
                skills = []
                for skill in event.skillList:
                    skills.append(skill.skillName)
                mentors = []
                for men in event.mentorList:
                    mentors.append({'first_name':men.first_name,})
                sd = json.dumps(event.startdate, cls=DjangoJSONEncoder)
                ed = json.dumps(event.enddate, cls=DjangoJSONEncoder)
                myEvent = {
                    'startdate':sd,
                    'enddate':ed,
                    'id':event.id,
                    'user':myUser,
                    'eventName':event.eventName,
                    'eventDescription':event.description,
                    'skillList':skills,
                    'mentorList':mentors,
                }
                myevents.append(myEvent)

            return HttpResponse(json.dumps(myevents),mimetype="application/json")
    else:
        return redirect("/auth/")


@csrf_exempt
def categorise(data):
    eventList = set()
    times = [int(x) for x in data['eventList']]
    events=[]
    x = datetime.now()
    x = x.strftime("%Y-%m-%d")
    upevents=[]
    pastevents=[]
    todayevents=[]
#    print x
#    print "hello"
    e = Event.objects.all()
    for event in e:
        if 1 in times:
            if(event.startdate.strftime("%Y-%m-%d") > x):
                upevents.append(event)
#                print "upcoming"
        if 2 in times:
            if(event.startdate.strftime("%Y-%m-%d") < x):
                pastevents.append(event)
#                print "past"
        if 3 in times:
            if(event.startdate.strftime("%Y-%m-%d") == x):
                todayevents.append(event)
#                print "today"
    
    events=[]
    events=upevents+pastevents+todayevents
    print events
    print data['pageNo']
    paginator = Paginator(events,3)
    eventList = paginator.page(data['pageNo'])
    eventList = eventList.object_list
    myEvents = []
#    print "lollllllz"
    for event in eventList:
        myUser = {
            'first_name':event.user.first_name,
            'last_name':event.user.last_name
        }
        skills = []
        for skill in event.skillList:
            skills.append(skill.skillName)
        mentors = []
        for men in event.mentorList:
            mentors.append({'first_name':men.first_name,})
        sd = json.dumps(event.startdate, cls=DjangoJSONEncoder)
        ed = json.dumps(event.enddate, cls=DjangoJSONEncoder)
        myEvent = {
            'startdate':sd,
            'enddate':ed,
            'id':event.id,
            'user':myUser,
            'eventName':event.eventName,
            'eventDescription':event.description,
            'skillList':skills,
            'mentorList':mentors,
        }
        myEvents.append(myEvent)
#    print "lol"
    return HttpResponse(json.dumps(myEvents),mimetype="application/json")

templates/event/addevent.html
{% extends 'base/base.html' %}
{% block title %}
Add Event
{% endblock %}

{% block content %}
{% if error  %}
<div class="chip">
	<div class = "material-icons">error_outline</div>{{error}}
	<i class="material-icons">close</i>
</div>
{% endif %}
{% load staticfiles %}
<div class = "container thin-letters-3">
<div class = "row">
<div class='col m8 l8 s8 offset-m2 offset-l2'>	
	{% csrf_token %}
	<div class = "row center-align">
		<h3 class = "thin-letters-3" >Add Event</h3>
	</div>
	<div class = "divider"></div>
	<div class = "section"></div>
	<div class = "row">
		<div class="input-field">
			<input type="text" class="validate" name="eventname" id="eventname" required="true">
			<label for="eventname">Event Name</label>
		</div>
	</div>
	<div class = "row">
		<div class="input-field">
			<textarea id="eventDescription" class="materialize-textarea"></textarea>
			<label for="description">Event Description</label>
		</div>
	</div>

    <div class = "row">
		<div class="input-field col s6 m6 l6">
            <label for="startdate">Start Date</label>
            <input type="date" class="datepicker" id="sdate">
		</div>
        <div class="input-field col s6 m6 l6">
			<label for="enddate">End Date</label>
            <input type="date" class="datepicker" id="edate">
		</div>
	</div>
    
    <div class = "row">
		<div class="input-field">
			<textarea id="organiser" class="materialize-textarea"></textarea>
			<label for="organiser">Organiser</label>
		</div>
	</div>

	<div class="row">
		
			<h4>Technologies to be Used</h4>
			<table id="skills">
				<thead>
					<tr>
						<th>Technologies</th>
						<th>Working with</th>
					</tr>
				</thead>
				<tbody>
					{% for skill in skills %}
					<tr>
						<td>{{skill.skillName}}</td>
						<td>
							<div class="switch">
								<label>
									No
									<input type="checkbox" skillId={{skill.id}}>
									<span class="lever"></span>
									Yes
								</label>
							</div>
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
	</div>

	<div class="row">
		
			<h4>Mentors</h4>
			{% if users|length == 0%}
				<p>There are no registered users yet.</p>
			</div></div>
			{% else %}
			<table id="mentors">
				<thead>
					<tr>
						<th>Users</th>
						<th>Working with</th>
					</tr>
				</thead>

				<tbody>
					{% for user in users %}
					<tr>
						<td>{{user.username}} {% if user.username == username%}(Me){% endif %}</td>
						<td>
							<div class="switch">
								<label>
									No
									<input type="checkbox" username={{user.username}} {% if user.username == username%}checked disabled{% endif %}>
									<span class="lever"></span>
									Yes
								</label>
							</div>
						</td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		
	</div>
	{% endif %}	

	<div class = "row">
		<div class="col s6">
			<button class="btn waves-effect waves-light" id="addEvent" type="button">Add Event</button>
		</div>
	</div>
</div>

<div>
<script type="text/javascript" src = "{% static 'js/event/main.js' %}"></script>
</div>

{% endblock %}

templates/event/showevent.html
{% extends 'base/base.html' %}
{% load staticfiles %}
{% block title %}
Events
{% endblock %}
{% block content %}

{% csrf_token %}
<script type="text/javascript" src = "{% static 'js/event/main.js' %}"></script>

<!-- <h5>Projects - (Showing {{projects|length}} projects )<a href="addProject/">Add project</a></h5> --> 
<div class = "section"></div>
<div class="row thin-letters-3">
	<div class="col s12 m6 l6 offset-m1 offset-l1 eventList" pageNo = '2' cpageNo ="1" >
		<div class = "row">
			<div class = "col m4 l4">
				<span class = "thin-letters-2" style = "font-size:40px">Event</span> 
			</div>
            
            {% if username == "priyam" %}
            <div class = "col m2 l2 offset-l6 offset-m6">
				<a href="http://127.0.0.1:8000/event/addEvent/" class="btn-floating btn-large tooltipped waves-effect waves-light teal" data-position="bottom" data-delay="50" data-tooltip="Add Event"><i class="material-icons">add</i></a>
			</div>
            {% endif %}
            
		</div>
		<div class = "divider"></div>
		<div class = "section"></div>
        
		<div class = "all">
        
		{% for event in events %}

		<div class = "row">
			<a href="#" >
<!--                viewEvent/?eventId={{event.id}}-->
				<script>
					colorDiv();
				</script>

				<div class="card-content">
					<div class = "row">
						<span class="card-title">{{event.eventName}}</span>
						<div class = "divider"></div>
						<div class = "section"></div>
					</div>
                    
                <div  class="row">  
                    
<!--
                    <div class="col s6 m6 l6">
                        <img src="{% static 'images/event_images/eventimg.jpg' %}" style="height:150px; width:250px">
                    </div>
-->
                    
                    <div class="col s6 m6 l6">
                    
                    <div class = "row" style = "margin-bottom:0;margin-left:-10px">
                        <div class = "col m12 s12 l12">
                        <p><b>{{event.user.first_name}} {{event.user.last_name}}</b></p>
                        <p class = 'desp'> {{event.eventDescription}}</p>
                        </div>
                    </div>
                    
					<div class = "row" style = "margin-bottom:0;margin-left:-10px">
						<div class = "col m12 s12 l12">
							<p class="white-text ">
								{% if event.startdate %}
								starts on : {{event.startdate}}
								{% endif %}
								<br/>
                                {% if event.enddate %}
								ends on : {{event.enddate}}
								{% endif %}
							</p>
					   </div>
				    </div>
                        
                    </div>
                    
<!--
                    <div class="col s6 m6 l6">
                        <img src="{% static 'images/event_images/eventimg.jpg' %}" style="height:200px; width:250px">
                    </div>
-->
                    
                </div>  
                    
			</div>
				
						
					
					


				<div class="card-action">
					{% for skill in event.skillList %}
					<div class="chip skill" skillName = "{{skill.skillName}}">
						{{skill.skillName}}
					</div>
					{% endfor %}

				</div>
			</div>
		</div>
	</a>
	<script>	
		$(".desp").text(function(index, currentText) {
			return currentText.substr(0, 180);
		});
	</script>

	{% endfor %}
	</div>
	<div class = "loadMore col offset-m4 offset-s4" style="cursor:pointer"><a class="waves-effect waves-light btn"><i class="material-icons right">system_update_alt</i>Load More</a></div>
    
    <div class="category">
    
    </div>

</div>


<div class = "col m4 l4 s12 offset-l1 offset-m1">
	<!-- Search bar starts -->
	<div class = "row">
		<nav class = "col m10 l10 s10 green lighten-1">
			<div class="nav-wrapper">
				<form class = "searchForm" action = "{% url 'searchig:queryFromDash'%}" method = "get">
					<div class="input-field">
						<input id="search" name="search" class="searchWords" type="search" placeholder = "Search" required>
						<label for="search"><a class = "submitAnchor"><i class="material-icons" style= "cursor:pointer">search</i></a></label>
						<i class="material-icons">close</i>
					</div>
				</form>
			</div>
		</nav>
	</div>
    
<!--    dates category   -->
    <div class = "row">
		<div class = "col m10 l10 s10 timebox">

			<div class="row collapsible">
				<p class = "thin-letters-1" style="font-size:15px;padding-left:8%"><b>Category</b></p>
				<div class = "row" style = "padding-left:8%">
				<ul>
					<li>
						<div class="collapsible-"> 
							<p>
     					 		<input type="checkbox" id = "e1" eId = "0" checked = "1"/>
     					 		<label class = "thin-letters-3" for="e1">All</label>
    						</p>
    				</div>

					</li>

					<li>
						<div class="collapsible-"> 
							<p>
     					 		<input type="checkbox" id="e2" eId = "1"/>
     					 		<label class = "thin-letters-3" for="e2">Upcoming Events</label>
    						</p>
    				</div>

					</li>
					<li>
						<div class=""> 
							<p>
     					 		<input type="checkbox" id="e3" eId  = "2"/>
     					 		<label for="e3">Past Events</label>
    						</p>
    				</div>

					</li>
					<li>
						<div class=""> 
							<p>
     					 		<input type="checkbox" id="e4" eId = "3"/>
     					 		<label for="e4">Today's Events</label>
    						</p>
    				</div>

					</li>
										
				</ul>
			</div>
			</div>
		</div>
	</div>


	<!-- similar users -->
	<div class = "row">
		<div class = "col m10 l10 s10" style="padding:0">

			<div class="row collapsible" data-collapsible="accordion">
				<p class = "thin-letters-3" style="font-size:15px;padding-left:8%"><b>Other Users</b></p>

				<ul>
                    {% for u in users %}
                    <li>
						<div class="collapsible-header"><i class="material-icons">perm_identity</i>{{u.username}}</div>

					</li>
                    {% endfor %}
<!--
					<li>
						<div class="collapsible-header"><i class="material-icons">perm_identity</i>First</div>

					</li>
					<li>
						<div class="collapsible-header"><i class="material-icons">perm_identity</i>Second</div>

					</li>
					<li>
						<div class="collapsible-header"><i class="material-icons">perm_identity</i>Third</div>

					</li>
-->
				</ul>
			</div>
		</div>
	</div>

	<!-- Popular projects -->
<!--
	<div class = "row">
		<div class = "col m10 l10 s10" style="padding:0">

			<div class="row collapsible" data-collapsible="accordion">
				<p class = "thin-letters-3" style="font-size:15px;padding-left:8%"><b>Popular Projects</b></p>

				<ul>
					<li>
						<div class="collapsible-header"><i class="material-icons">perm_media</i>First</div>

					</li>
					<li>
						<div class="collapsible-header"><i class="material-icons">perm_media</i>Second</div>

					</li>
					<li>
						<div class="collapsible-header"><i class="material-icons">perm_media</i>Third</div>

					</li>
				</ul>
			</div>
		</div>
	</div>
-->


</div>
</div>
<div id="ratemodal" class="modal ">
	<div class="modal-content" style="cursor:pointer">
		<div class="row">
			<div class="center-align" >
				{% for i in "xxxxx" %}
				<i class="large stars material-icons" id="">stars</i>
				{%endfor%}
			</div>
		</div>

		
	</div>
	
</div>




<script type="text/javascript">
	

</script>





{% endblock%}